# Generated by Django 3.0.7 on 2020-06-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(max_length=200)),
                ('word_meaning_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='dictionary_django.term')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
